### ISSUE TITLE
PHP Fatal error from broken error reporting methods 

### ISSUE THREAD

**Issue by jerturowetz** [contentstack/contentstack-php#35]
The following code was working until earlier last week:
```
$stack_tool = $stack->ContentType( 'connector' )->Query()->toJSON()->containedIn( 'SOMEKEY', 'SOMEVAL' )->find();
```

and now is resulting in a php fatal error:
```PHP Fatal error:  Uncaught Exception: value must be an array in .../contentstack/contentstack/src/Support/helper.php:27```

The strange thing is the error is coming from an error reporting method (`contentstackCreateError`) which doesn't seem set up to handle the types which could be passed to it:

```[28-Aug-2023 02:47:44 UTC] PHP Fatal error:  Uncaught Exception: value must be an array in /var/www/html/wp-content/themes/unito/libs/contentstack/contentstack/src/Support/helper.php:27
Stack trace:
#0 /var/www/html/wp-content/themes/unito/libs/contentstack/contentstack/src/Stack/BaseQuery.php(775): contentstackCreateError('value must be a...')
#1 /var/www/html/wp-content/themes/unito/includes/cron/update-connectors.php(80): Contentstack\Stack\BaseQuery->containedIn('pcd.provider_na...', NULL)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(83) : eval()'d code(35): Unito\Includes\Cron\UpdateConnectors\refresh_tool_additional_content(Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(83): eval()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(57): EvalFile_Command::execute_eval('/var/www/html/....', Array, false)
#5 [internal function]: EvalFile_Command->__invoke(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(431): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(454): WP_CLI\Runner->run_command(Array, Array)
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(131): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1202): WP_CLI\Runner->do_early_invoke('before_wp_load')
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#17 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#18 {main}
  thrown in /var/www/html/wp-content/themes/unito/libs/contentstack/contentstack/src/Support/helper.php on line 27
Fatal error: Uncaught Exception: value must be an array in /var/www/html/wp-content/themes/unito/libs/contentstack/contentstack/src/Support/helper.php:27
Stack trace:
#0 /var/www/html/wp-content/themes/unito/libs/contentstack/contentstack/src/Stack/BaseQuery.php(775): contentstackCreateError('value must be a...')
#1 /var/www/html/wp-content/themes/unito/includes/cron/update-connectors.php(80): Contentstack\Stack\BaseQuery->containedIn('pcd.provider_na...', NULL)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(83) : eval()'d code(35): Unito\Includes\Cron\UpdateConnectors\refresh_tool_additional_content(Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(83): eval()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(57): EvalFile_Command::execute_eval('/var/www/html/....', Array, false)
#5 [internal function]: EvalFile_Command->__invoke(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(431): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(454): WP_CLI\Runner->run_command(Array, Array)
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(131): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1202): WP_CLI\Runner->do_early_invoke('before_wp_load')
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#17 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#18 {main}
  thrown in /var/www/html/wp-content/themes/unito/libs/contentstack/contentstack/src/Support/helper.php on line 27
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.```

**Comment by jerturowetz** [comment]
I can effectively patch the issue by messing about with the queries, replaced with:

```		$query1     = $stack->ContentType( 'connector' )->Query()->containedIn( 'pcd.provider_name', $unito_connector_names[ $tool_id ] )->getQuery();
		$stack_tool = $stack->ContentType( 'connector' )->Query()->toJSON()->addQuery( $query1 )->find();```

But this doesnt make me feel very confident, as if another type issue gets passed the whole thing will break again and even the error reporting will fail.

**Comment by ishaileshmishra** [comment]
Thank you for reaching out, @jerturowetz. We are currently investigating this matter and will provide updates on our progress here.

**Comment by ishaileshmishra** [comment]
Hello @jerturowetz , we've released a latest build that includes the fix for this issue. We're closing the ticket for now, but please feel free to reopen it if the problem persists.
